using System.Collections.Immutable;
using System.Text;
using FluentRoslyn.Builders;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FluentRoslyn.Example.Generator;

[Generator]
public class HelloSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node).Where(x => x is not null);

        var compilation = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(compilation, Execute);
    }

    private void Execute(SourceProductionContext context, (Compilation Left, ImmutableArray<ClassDeclarationSyntax> Right) arg2)
    {
        // Both generated types go in one file, which is what SourceFile is for: they
        // share a namespace and one set of usings, and the whole thing is a single
        // AddSource call.
        var file = SourceFile.InNamespace("FluentRoslyn.Example.App");

        // A constructor-assigned class built with typed references: the property and
        // parameter are handles sharing a type argument, so assigning the wrong one
        // into Text would fail to compile *here*, in the generator, rather than
        // producing broken generated source.
        var greeting = file.Class("Greeting");
        var text = greeting.DefineProperty<string>("Text").GetOnly();

        greeting.DefineConstructor(AccessModifier.Public)
            .WithParameter<string>("text", out var textParam)
            .Assign(text, textParam);

        // The partial method's body is built through the fluent API too, rather than
        // grafting a ParseMemberDeclaration string onto the raw tree. Its greeting
        // routes through the Greeting class above, so CI's assertion on the app's
        // output exercises Assign end-to-end.
        var program = file.Class("Program").Static().Partial();

        program.DefineMethod("HelloFrom", AccessModifier.None).WithParameter<string>("name")
            .Static().Partial()
            .AsExpressionBody("""System.Console.WriteLine(new Greeting($"Generator says: Hi from '{name}'").Text)""");

        context.AddSource("Generated.g.cs",
            SourceText.From("// <auto-generated/>\n" + file, Encoding.UTF8));
    }
}
