using System.Collections.Immutable;
using System.Text;
using FluentRoslyn.Builders;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FluentRoslyn.Example.Generator;

[Generator]
public class HelloSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node).Where(x => x is not null);

        var compilation = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(compilation, Execute);
    }

    private void Execute(SourceProductionContext context, (Compilation Left, ImmutableArray<ClassDeclarationSyntax> Right) arg2)
    {
        // A constructor-assigned class built with typed references: the property and
        // parameter are handles sharing a type argument, so assigning the wrong one
        // into Text would fail to compile *here*, in the generator, rather than
        // producing broken generated source.
        var greeting = NamespaceBuilder.Get("FluentRoslyn.Example.App").Class("Greeting");
        var text = greeting.DefineProperty<string>("Text").GetOnly();

        greeting.DefineConstructor(AccessModifier.Public)
            .WithParameter<string>("text", out var textParam)
            .Assign(text, textParam);

        context.AddSource("Greeting.g.cs",
            SourceText.From("// <auto-generated/>\n" + greeting, Encoding.UTF8));

        // Build the whole file with FluentRoslyn's fluent API — including the partial method
        // body — instead of grafting a ParseMemberDeclaration string onto the raw tree.
        // The greeting text routes through the generated Greeting class above, so the
        // end-to-end assertion on the app's output also exercises Assign.
        var program = NamespaceBuilder.Get("FluentRoslyn.Example.App")
            .Class("Program").Static().Partial();

        program.DefineMethod("HelloFrom", AccessModifier.None).WithParameter<string>("name")
            .Static().Partial()
            .AsExpressionBody("""System.Console.WriteLine(new Greeting($"Generator says: Hi from '{name}'").Text)""");

        var code = "// <auto-generated/>\n" + program;

        context.AddSource("Program.g.cs", SourceText.From(code, Encoding.UTF8));
    }
}
