using System.Linq;
using System.Text;
using FluentRoslyn.Builders;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FluentRoslyn.Example.Builders.Generator;

/// <summary>
/// Generates a fluent builder for any type marked <c>[GenerateBuilder]</c>, driven by
/// that type's longest public constructor: a field and a <c>With…</c> setter per
/// parameter, and a <c>Build()</c> that calls the constructor.
/// </summary>
/// <remarks>
/// <para>
/// This is the first example written against the <em>consumer's</em> types rather than
/// a shape the generator invented, which is the case most real generators are. Those
/// types are <c>ISymbol</c>s discovered when the generator runs: they have no CLR type
/// and no builder, so nothing keyed to <c>&lt;T&gt;</c> can reach them. Every member
/// here is declared through the raw-name overloads for exactly that reason.
/// </para>
/// <para>
/// The two remaining raw-text spots are marked below and tracked as roadmap #30 and
/// #31. They are worth seeing: this is precisely where the typed surface still stops
/// for a symbol-driven generator, and writing the generator is what showed it.
/// </para>
/// </remarks>
[Generator]
public class BuilderGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
        // <auto-generated/>
        namespace FluentRoslyn.Example.Builders
        {
            /// <summary>Generates a fluent builder for this type, from its constructor.</summary>
            [System.AttributeUsage(System.AttributeTargets.Class)]
            internal sealed class GenerateBuilderAttribute : System.Attribute
            {
            }
        }
        """;

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("GenerateBuilderAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            "FluentRoslyn.Example.Builders.GenerateBuilderAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(targets, Emit);
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol type)
    {
        var constructor = type.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public && c.Parameters.Length > 0)
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault();

        if (constructor is null)
            return;

        var file = SourceFile.InNamespace(type.ContainingNamespace.ToDisplayString());
        var builder = file.Class($"{type.Name}Builder")
            .WithSummary($"Fluent builder for {type.Name}.");

        var built = Qualified(type);

        foreach (var parameter in constructor.Parameters)
        {
            var parameterType = Qualified(parameter.Type);
            var field = $"_{parameter.Name}";

            // The consumer's type is an ISymbol, never a T, so the field's type is
            // named by text. Everything structural is still built rather than
            // concatenated -- modifiers, docs, the declaration itself.
            builder.DefineField(field, parameterType)
                .WithSummary($"Backing value for {parameter.Name}.");

            builder.DefineMethod($"With{Capitalise(parameter.Name)}")
                .WithSummary($"Sets {parameter.Name}.")
                .WithParameter(parameter.Name, parameterType)
                .Returns(builder)
                // GAP (roadmap #30): both sides are consumer-typed, so there is no
                // IReference<T> for either and Assign cannot be used; and `this` is not
                // modelled as a reference, so the fluent return is text too.
                .AddStatement($"{field} = {parameter.Name};")
                .AddStatement("return this;");
        }

        var arguments = string.Join(", ", constructor.Parameters.Select(p => $"_{p.Name}"));

        builder.DefineMethod("Build")
            .WithSummary($"Builds the {type.Name}.")
            .Returns(built)
            // GAP (roadmap #31): AsConstructable derives a handle from a
            // ConstructorBuilder, and this constructor belongs to the consumer, so
            // Value.New has nothing to work from.
            .AddStatement($"return new {built}({arguments});");

        context.AddSource($"{type.Name}Builder.g.cs",
            SourceText.From("// <auto-generated/>\n" + file, Encoding.UTF8));
    }

    private static string Qualified(ISymbol symbol)
        => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string Capitalise(string name)
        => name.Length == 0 ? name : char.ToUpperInvariant(name[0]) + name.Substring(1);
}
