using System.Collections.Generic;
using System.Linq;
using System.Text;
using FluentRoslyn.Abstractions;
using FluentRoslyn.Builders;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FluentRoslyn.Example.Builders.Generator;

/// <summary>
/// Generates a fluent builder for any type marked <c>[GenerateBuilder]</c>, driven by
/// that type's longest public constructor: a field and a <c>With…</c> setter per
/// parameter, and a <c>Build()</c> that calls the constructor.
/// </summary>
/// <remarks>
/// <para>
/// This is the first example written against the <em>consumer's</em> types rather than
/// a shape the generator invented, which is the case most real generators are. Those
/// types are <c>ISymbol</c>s discovered when the generator runs: they have no CLR type
/// and no builder, so nothing keyed to <c>&lt;T&gt;</c> can reach them. Every member
/// here is declared through the raw-name overloads for exactly that reason.
/// </para>
/// <para>
/// Nothing here is parsed from text: every declaration, the assignment, the fluent
/// <c>return this</c>, and the constructor call in <c>Build</c> are all built. What is
/// <em>not</em> available is the compile-time checking, because none of these types
/// exist as <c>T</c> — the assignment compares declared type text and the constructor
/// call is unchecked, both when the generator runs. That is the honest ceiling for a
/// symbol-driven generator, and it is a different thing from emitting strings.
/// </para>
/// </remarks>
[Generator]
public class BuilderGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
        // <auto-generated/>
        namespace FluentRoslyn.Example.Builders
        {
            /// <summary>Generates a fluent builder for this type, from its constructor.</summary>
            [System.AttributeUsage(System.AttributeTargets.Class)]
            internal sealed class GenerateBuilderAttribute : System.Attribute
            {
            }
        }
        """;

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("GenerateBuilderAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            "FluentRoslyn.Example.Builders.GenerateBuilderAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(targets, Emit);
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol type)
    {
        var constructor = type.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public && c.Parameters.Length > 0)
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault();

        if (constructor is null)
            return;

        var file = SourceFile.InNamespace(type.ContainingNamespace.ToDisplayString());
        var builder = file.Class($"{type.Name}Builder")
            .WithSummary($"Fluent builder for {type.Name}.");

        var built = Qualified(type);
        var fields = new List<IValue>();

        foreach (var parameter in constructor.Parameters)
        {
            var parameterType = Qualified(parameter.Type);

            // The consumer's type is an ISymbol, never a T, so the field's type is
            // named by text. Everything structural is still built rather than
            // concatenated -- modifiers, docs, the declaration itself.
            var field = builder.DefineField($"_{parameter.Name}", parameterType)
                .WithSummary($"Backing value for {parameter.Name}.");

            fields.Add(field);

            builder.DefineMethod($"With{Capitalise(parameter.Name)}")
                .WithSummary($"Sets {parameter.Name}.")
                .WithParameter(parameter.Name, parameterType, out var argument)
                .Returns(builder)
                // Both sides are consumer-typed, so there is no shared T -- but their
                // declared type text is compared, which catches assigning the wrong
                // parameter into the wrong field.
                .AssignRaw(field, argument)
                .Return(builder.This());
        }

        builder.DefineMethod("Build")
            .WithSummary($"Builds the {type.Name}.")
            .Returns(built)
            // The consumer's constructor has no ConstructorBuilder, so nothing about its
            // signature can be checked -- but the call is still built rather than
            // concatenated, and every argument name comes from the field that declared
            // it rather than from a second round of string formatting.
            .Return(Value.NewOfType(built, fields.ToArray()));

        context.AddSource($"{type.Name}Builder.g.cs",
            SourceText.From("// <auto-generated/>\n" + file, Encoding.UTF8));
    }

    private static string Qualified(ISymbol symbol)
        => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string Capitalise(string name)
        => name.Length == 0 ? name : char.ToUpperInvariant(name[0]) + name.Substring(1);
}
