// Calc does not exist in this project's source. It was generated by
// FluentRoslyn.Example.Templates.Generator, whose method bodies were in turn lifted
// from compiled [Template] methods by the FluentRoslyn.Templates meta-generator.
using FluentRoslyn.Example.Templates.App;

Console.WriteLine($"Add: {Calc.Add(2, 3)}");
Console.WriteLine($"Describe: {Calc.Describe("Cart", 4)}");
Console.WriteLine($"IsEmpty: {Calc.IsEmpty("   ")}");
Console.WriteLine($"Tag: {Calc.Tag("sale")}");
