using System.Collections.Immutable;
using System.Text;
using Generatr.Builders;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Generatr.Example.Generator;

[Generator]
public class HelloSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node).Where(x => x is not null);

        var compilation = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(compilation, Execute);
    }

    private void Execute(SourceProductionContext context, (Compilation Left, ImmutableArray<ClassDeclarationSyntax> Right) arg2)
    {
        // Build the whole file with Generatr's fluent API — including the partial method
        // body — instead of grafting a ParseMemberDeclaration string onto the raw tree.
        var program = NamespaceBuilder.Get("Generatr.Example.App")
            .Class("Program").Static().Partial();

        program.DefineMethod("HelloFrom", AccessModifier.None).WithParameter<string>("name")
            .Static().Partial()
            .AsExpressionBody("""System.Console.WriteLine($"Generator says: Hi from '{name}'")""");

        var code = "// <auto-generated/>\n" + program;

        context.AddSource("Program.g.cs", SourceText.From(code, Encoding.UTF8));
    }
}
