using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Generatr.Builders;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Generatr.Example.Generator;

[Generator]
public class HelloSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node).Where(x => x is not null);

        var compilation = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(compilation, Execute);
    }

    private void Execute(SourceProductionContext context, (Compilation Left, ImmutableArray<ClassDeclarationSyntax> Right) arg2)
    {
        // Build the class shell with Generatr's fluent API.
        var compilationUnit = NamespaceBuilder.Get("Generatr.Example.App")
            .Class("Program").Static().Partial()
            .BuildCompilationUnit();

        // Statement-bearing members aren't expressible through the fluent API yet;
        // BuildCompilationUnit exposes the raw syntax tree as the escape hatch.
        var programClass = compilationUnit.DescendantNodes().OfType<ClassDeclarationSyntax>().First();
        var helloFrom = (MethodDeclarationSyntax)ParseMemberDeclaration(
            """static partial void HelloFrom(string name) => System.Console.WriteLine($"Generator says: Hi from '{name}'");""")!;

        var code = compilationUnit
            .ReplaceNode(programClass, programClass.AddMembers(helloFrom))
            .NormalizeWhitespace(eol: "\n")
            .WithLeadingTrivia(Comment("// <auto-generated/>"), LineFeed)
            .ToFullString();

        context.AddSource("Program.g.cs", SourceText.From(code, Encoding.UTF8));
    }
}
