using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using Generatr.Builders;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Generatr.Example.Generator;

[Generator]
public class HelloSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node).Where(x => x is not null);

        var compilation = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(compilation, Execute);
    }

    private void Execute(SourceProductionContext context, (Compilation Left, ImmutableArray<ClassDeclarationSyntax> Right) arg2)
    {
        var namespaceBuilder = NamespaceBuilder.Get("Generatr.Example.App");
        var classBuilder = namespaceBuilder.Class("Program").Static().Partial();
        var theCode = """
            // <auto-generated/>
            using System;

            namespace Generatr.Example.App;

            public static partial class Program
            {
                        static partial void HelloFrom(string name) =>
                            Console.WriteLine($"Generator says: Hi from '{name}'");
            }

            """;

        context.AddSource("Program.g.cs", theCode);
    }


}
