using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FluentRoslyn.Templates;

/// <summary>
/// The meta-generator. It runs on a <em>source-generator project</em>, finds methods
/// marked <c>[Template]</c>, and lifts each into the FluentRoslyn calls that reproduce
/// it — so the template's body is real, compiled, refactorable C# rather than a string.
/// </summary>
/// <remarks>
/// <para>
/// This is legal because a generator project is an ordinary library at its own build
/// time. The <c>netstandard2.0</c> rule constrains what a generator <em>is</em> — it
/// loads into the compiler process — not what it runs <em>on</em>. And the rule that
/// generators cannot see each other's output applies within one compilation; a
/// meta-generator and its target are two.
/// </para>
/// <para>
/// What this buys, measured: breaking a template is <c>CS0103</c> and a failed build in
/// the template author's own compile. The hand-written string it replaces fails as
/// <c>CS8785</c> — a warning, in the consumer's build, which succeeds with the generated
/// code silently missing. See <c>docs/DESIGN-templates.md</c>.
/// </para>
/// </remarks>
[Generator]
public sealed class TemplateLifter : IIncrementalGenerator
{
    private const string TemplateAttributeSource = """
        // <auto-generated/>
        namespace FluentRoslyn.Templates
        {
            /// <summary>
            /// Marks a static method whose body is a template: real C# that the
            /// FluentRoslyn.Templates meta-generator lifts into the builder calls that
            /// reproduce it. The method is never invoked — it exists so the compiler
            /// checks the body.
            /// </summary>
            [System.AttributeUsage(System.AttributeTargets.Method)]
            internal sealed class TemplateAttribute : System.Attribute
            {
            }
        }
        """;

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The attribute ships as source rather than in a referenced assembly, so the
        // package stays a pure analyzer with nothing flowing to the consumer.
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("TemplateAttribute.g.cs", SourceText.From(TemplateAttributeSource, Encoding.UTF8)));

        var templates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "FluentRoslyn.Templates.TemplateAttribute",
            predicate: static (node, _) => node is MethodDeclarationSyntax,
            transform: static (ctx, _) => Describe(ctx));

        context.RegisterSourceOutput(templates.Collect(), Emit);
    }

    private static TemplateModel Describe(GeneratorAttributeSyntaxContext context)
    {
        var syntax = (MethodDeclarationSyntax)context.TargetNode;
        var symbol = (IMethodSymbol)context.TargetSymbol;
        var containing = symbol.ContainingType;
        var location = syntax.Identifier.GetLocation();

        var problems = new List<Diagnostic>();

        if (!symbol.IsStatic)
            problems.Add(Diagnostic.Create(TemplateDiagnostics.MustBeStatic, location, symbol.Name));

        if (symbol.TypeParameters.Length > 0)
            problems.Add(Diagnostic.Create(TemplateDiagnostics.NoGenerics, location, symbol.Name));

        if (syntax.ExpressionBody is null)
            problems.Add(Diagnostic.Create(TemplateDiagnostics.NeedsExpressionBody, location, symbol.Name));

        // The emitters are generated into the other half of the containing type, so it
        // has to be partial -- and static, since the emitters are.
        var isPartial = containing.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(t => t.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)));

        if (!isPartial || !containing.IsStatic)
            problems.Add(Diagnostic.Create(
                TemplateDiagnostics.ContainingTypeMustBePartial, location, containing.Name));

        return new TemplateModel(
            Namespace: containing.ContainingNamespace.IsGlobalNamespace
                ? null
                : containing.ContainingNamespace.ToDisplayString(),
            ContainingType: containing.Name,
            MethodName: symbol.Name,
            ReturnType: symbol.ReturnsVoid ? null : Display(symbol.ReturnType),
            Parameters: symbol.Parameters
                .Select(p => new TemplateParameter(Display(p.Type), p.Name))
                .ToImmutableArray(),
            Body: syntax.ExpressionBody is null
                ? string.Empty
                : QualifyTypes(syntax.ExpressionBody.Expression, context.SemanticModel),
            Problems: problems.ToImmutableArray());
    }

    // The body is lifted as text into a file with none of the template's using
    // directives, so an unqualified `StringBuilder` would emit as-is and fail in the
    // *consumer's* build with CS0246 -- measured, before this rewrite existed. Binding
    // every type reference to its fully qualified name here makes the body
    // self-contained, which is the same choice the builder API makes everywhere else:
    // fully qualified is always correct, and SimplifyTypeNames() opts into shortening.
    private static string QualifyTypes(ExpressionSyntax body, SemanticModel model)
        => new TypeQualifier(model).Visit(body).ToString();

    private sealed class TypeQualifier : Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter
    {
        private readonly SemanticModel _model;

        internal TypeQualifier(SemanticModel model)
        {
            _model = model;
        }

        public override SyntaxNode? VisitIdentifierName(IdentifierNameSyntax node)
            => Qualified(node) ?? base.VisitIdentifierName(node);

        public override SyntaxNode? VisitGenericName(GenericNameSyntax node)
            // A qualified display string carries the type arguments too, so the whole
            // node is replaced rather than recursed into.
            => Qualified(node) ?? base.VisitGenericName(node);

        private SyntaxNode? Qualified(SimpleNameSyntax node)
        {
            // The right-hand side of `a.B` or `A.B` is a member or an already-qualified
            // name; rewriting it would produce `a.global::Ns.B`.
            if (node.Parent is MemberAccessExpressionSyntax member && member.Name == node) return null;
            if (node.Parent is QualifiedNameSyntax qualified && qualified.Right == node) return null;

            if (_model.GetSymbolInfo(node).Symbol is not ITypeSymbol type) return null;

            // A type parameter has no qualified name to bind to, and templates cannot be
            // generic anyway (FRT004).
            if (type.TypeKind == TypeKind.TypeParameter) return null;

            return Microsoft.CodeAnalysis.CSharp.SyntaxFactory
                .ParseTypeName(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .WithTriviaFrom(node);
        }
    }

    // Fully qualified with the global:: alias, because the emitted file carries none of
    // the template file's using directives and must not depend on them.
    private static string Display(ITypeSymbol type)
        => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static void Emit(SourceProductionContext context, ImmutableArray<TemplateModel> templates)
    {
        if (templates.IsDefaultOrEmpty)
            return;

        foreach (var problem in templates.SelectMany(t => t.Problems))
            context.ReportDiagnostic(problem);

        var usable = templates.Where(t => t.Problems.IsEmpty).ToImmutableArray();

        foreach (var group in usable.GroupBy(t => (t.Namespace, t.ContainingType)))
        {
            var source = BuildEmitters(group.Key.Namespace, group.Key.ContainingType, group.ToImmutableArray());
            var hint = group.Key.Namespace is null
                ? $"{group.Key.ContainingType}.Templates.g.cs"
                : $"{group.Key.Namespace}.{group.Key.ContainingType}.Templates.g.cs";

            context.AddSource(hint, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string BuildEmitters(string? ns, string containingType, ImmutableArray<TemplateModel> templates)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("static partial class ").AppendLine(containingType);
        sb.AppendLine("{");

        for (var i = 0; i < templates.Length; i++)
        {
            if (i > 0) sb.AppendLine();
            AppendEmitter(sb, templates[i]);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // Every FluentRoslyn name below -- MethodBuilder, TypeBuilder, DefineMethod,
    // WithParameter, AsExpressionBody -- is a string literal, so no rename of them is
    // caught HERE: this project keeps compiling and the breakage lands in the code this
    // emits. What does catch it is the templates example, whose generator compiles the
    // lifted output as part of the solution build -- measured: renaming AsExpressionBody
    // is 58 CS1061 errors across the solution. That guard is only as wide as the
    // templates the example declares, which is why it deliberately includes a void one:
    // the void branch below emits different names (non-generic MethodBuilder, the
    // DefineMethod(string) overload) and every other template returns a value. An
    // earlier version of this comment claimed no rename broke anything in this
    // repository, which was wrong for five of the six names -- review finding R2-15.
    // The lockstep-versioning argument is unaffected: a consumer still cannot see this
    // coupling, so the matching version number still carries it. Renaming any of these?
    // Grep this file first, and keep the example's templates covering both branches.
    private static void AppendEmitter(StringBuilder sb, TemplateModel template)
    {
        var builderType = template.ReturnType is null
            ? "global::FluentRoslyn.Builders.MethodBuilder"
            : $"global::FluentRoslyn.Builders.MethodBuilder<{template.ReturnType}>";

        var define = template.ReturnType is null
            ? $"DefineMethod(\"{template.MethodName}\")"
            : $"DefineMethod<{template.ReturnType}>(\"{template.MethodName}\")";

        sb.Append("    /// <summary>Emits the <c>").Append(template.MethodName)
            .AppendLine("</c> template onto <paramref name=\"target\"/>.</summary>");
        sb.Append("    public static ").Append(builderType).Append(' ').Append("Emit")
            .Append(template.MethodName).AppendLine("(global::FluentRoslyn.Builders.TypeBuilder target)");
        sb.Append("        => target.").AppendLine(define);

        foreach (var parameter in template.Parameters)
            sb.Append("            .WithParameter<").Append(parameter.Type).Append(">(\"")
                .Append(parameter.Name).AppendLine("\")");

        sb.Append("            .AsExpressionBody(").Append(Verbatim(template.Body)).AppendLine(");");
    }

    // A verbatim literal, so the body's own quotes and backslashes survive intact. The
    // body is arbitrary C# text, which is exactly the input that breaks naive escaping.
    private static string Verbatim(string text)
        => "@\"" + text.Replace("\"", "\"\"") + "\"";

    private sealed record TemplateParameter(string Type, string Name);

    private sealed record TemplateModel(
        string? Namespace,
        string ContainingType,
        string MethodName,
        string? ReturnType,
        ImmutableArray<TemplateParameter> Parameters,
        string Body,
        ImmutableArray<Diagnostic> Problems);
}
