using System.Text;
using FluentRoslyn.Builders;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FluentRoslyn.Example.Templates.Generator;

/// <summary>
/// Generates a <c>Calc</c> class into the consuming app, with every method body coming
/// from a compiled template rather than a hand-written string.
/// </summary>
/// <remarks>
/// The <c>Templates.Emit…</c> methods called here do not exist in source: the
/// FluentRoslyn.Templates meta-generator produced them from the <c>[Template]</c>
/// methods, at this project's build time. So this generator is consuming generated code
/// while itself generating code — the three-level chain that makes the feature possible.
/// </remarks>
[Generator]
public class CalcGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(Execute);
    }

    private static void Execute(IncrementalGeneratorPostInitializationContext context)
    {
        var file = SourceFile.InNamespace("FluentRoslyn.Example.Templates.App");
        var calc = file.Class("Calc").Static();

        // Each of these lifts a template's signature *and* body onto the class. The
        // builder call is ordinary FluentRoslyn -- templates produce the same
        // MethodBuilder everything else does, so they compose with the rest of the API.
        Templates.EmitAdd(calc).Static();
        Templates.EmitDescribe(calc).Static();
        Templates.EmitIsEmpty(calc).Static();
        Templates.EmitTag(calc).Static();

        context.AddSource("Calc.g.cs",
            SourceText.From("// <auto-generated/>\n" + file, Encoding.UTF8));
    }
}
