using System.Text;
using FluentRoslyn.Builders;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FluentRoslyn.Example.ValueObjects.Generator;

/// <summary>
/// Fills in a partial struct marked <c>[ValueObject(typeof(T))]</c>: a wrapping
/// constructor, a <c>Value</c> property, and the equality and formatting members —
/// the strongly-typed-id pattern.
/// </summary>
/// <remarks>
/// <para>
/// The fourth example, and deliberately the <em>opposite</em> shape from the decorator.
/// Every marked type receives the identical member set; the only things that differ are
/// the value object's own name and its underlying type. Nothing varies in arity. That is
/// precisely the shape template holes were designed for, so this generator is the honest
/// test the decorator could not be — see <c>DESIGN-templates.md</c>.
/// </para>
/// <para>
/// One member resists: <c>Equals(object)</c> needs <c>obj is T other &amp;&amp;
/// Equals(other)</c>, which is a pattern match and a boolean operator. Those are on the
/// far side of the expression-grammar line the roadmap draws, so it stays raw text —
/// stated here rather than hidden behind a helper.
/// </para>
/// </remarks>
[Generator]
public class ValueObjectGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
        // <auto-generated/>
        namespace FluentRoslyn.Example.ValueObjects
        {
            /// <summary>Fills in this partial struct as a value object wrapping <c>underlying</c>.</summary>
            [System.AttributeUsage(System.AttributeTargets.Struct)]
            internal sealed class ValueObjectAttribute : System.Attribute
            {
                public ValueObjectAttribute(System.Type underlying) => Underlying = underlying;

                public System.Type Underlying { get; }
            }
        }
        """;

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("ValueObjectAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            "FluentRoslyn.Example.ValueObjects.ValueObjectAttribute",
            predicate: static (node, _) => node is StructDeclarationSyntax,
            transform: static (ctx, _) => (
                Type: (INamedTypeSymbol)ctx.TargetSymbol,
                Underlying: ctx.Attributes[0].ConstructorArguments[0].Value as INamedTypeSymbol));

        context.RegisterSourceOutput(targets, static (context, target) =>
        {
            if (target.Underlying is not null)
                Emit(context, target.Type, target.Underlying);
        });
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol type, INamedTypeSymbol underlying)
    {
        var self = Qualified(type);
        var wrapped = Qualified(underlying);

        var file = SourceFile.InNamespace(type.ContainingNamespace.ToDisplayString());

        // Partial and readonly must match the declaration the consumer wrote, or the two
        // halves are not the same type.
        var valueObject = file.Struct(type.Name)
            .Readonly()
            .Partial()
            .WithInterface($"global::System.IEquatable<{self}>")
            .WithSummary($"A value object wrapping {underlying.Name}.");

        var value = valueObject.DefineProperty("Value", wrapped)
            .GetOnly()
            .WithSummary("The wrapped value.");

        valueObject.DefineConstructor(AccessModifier.Public)
            .WithSummary("Wraps a value.")
            .WithParameter("value", wrapped, out var parameter)
            .AssignRaw(value, parameter);

        // Equals(T) -- the typed overload IEquatable<T> requires.
        valueObject.DefineMethod<bool>("Equals")
            .WithSummary("Compares against another value of the same kind.")
            .WithParameter("other", self, out var other)
            .ReturnRaw(Invocations.InvokeRaw(value, nameof(object.Equals), other.MemberRaw("Value")));

        // Equals(object) -- the one member the fluent API cannot express, because
        // `obj is T other && Equals(other)` is a pattern match and a boolean operator.
        valueObject.DefineMethod<bool>("Equals")
            .Override()
            .WithSummary("Compares against any object.")
            .WithParameter("obj", "object")
            .AsExpressionBody($"obj is {self} other && Equals(other)");

        valueObject.DefineMethod<int>("GetHashCode")
            .Override()
            .WithSummary("Hashes the wrapped value.")
            .ReturnRaw(Invocations.InvokeRaw(value, nameof(object.GetHashCode)));

        valueObject.DefineMethod<string>("ToString")
            .Override()
            .WithSummary("Formats the wrapped value.")
            .ReturnRaw(Invocations.InvokeRaw(value, nameof(object.ToString)));

        context.AddSource($"{type.Name}.g.cs",
            SourceText.From("// <auto-generated/>\n" + file, Encoding.UTF8));
    }

    private static string Qualified(ISymbol symbol)
        => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
}
