using System.Linq;
using System.Text;
using FluentRoslyn.Builders;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FluentRoslyn.Example.Decorator.Generator;

/// <summary>
/// Generates a logging decorator for any interface marked <c>[GenerateDecorator]</c>:
/// a sealed class implementing the interface, forwarding every member to an inner
/// instance and writing a line before each call.
/// </summary>
/// <remarks>
/// The third example, and the first whose member <em>bodies</em> follow one repeated
/// pattern that varies only in the member being forwarded to. That shape is what a
/// template hole is for, so this generator exists partly to find out whether template
/// holes are genuinely needed or merely plausible.
/// </remarks>
[Generator]
public class DecoratorGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
        // <auto-generated/>
        namespace FluentRoslyn.Example.Decorator
        {
            /// <summary>Generates a logging decorator that forwards to an inner instance.</summary>
            [System.AttributeUsage(System.AttributeTargets.Interface)]
            internal sealed class GenerateDecoratorAttribute : System.Attribute
            {
            }
        }
        """;

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("GenerateDecoratorAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            "FluentRoslyn.Example.Decorator.GenerateDecoratorAttribute",
            predicate: static (node, _) => node is InterfaceDeclarationSyntax,
            transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(targets, Emit);
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol iface)
    {
        var contract = Qualified(iface);
        var bareName = iface.Name.StartsWith("I") ? iface.Name.Substring(1) : iface.Name;

        var file = SourceFile.InNamespace(iface.ContainingNamespace.ToDisplayString());
        var decorator = file.Class($"Logging{bareName}")
            .Sealed()
            .WithInterface(contract)
            .WithSummary($"Logging decorator for {iface.Name}.");

        var inner = decorator.DefineField("_inner", contract).Readonly();

        decorator.DefineConstructor(AccessModifier.Public)
            .WithSummary("Wraps the instance being decorated.")
            .WithParameter("inner", contract, out var innerParameter)
            .ThrowIfNullRaw(innerParameter)
            .AssignRaw(inner, innerParameter);

        foreach (var member in iface.GetMembers())
        {
            switch (member)
            {
                case IMethodSymbol { MethodKind: MethodKind.Ordinary } method:
                    EmitMethod(decorator, method);
                    break;

                case IPropertySymbol { GetMethod: not null } property:
                    EmitProperty(decorator, property);
                    break;
            }
        }

        context.AddSource($"Logging{bareName}.g.cs",
            SourceText.From("// <auto-generated/>\n" + file, Encoding.UTF8));
    }

    private static void EmitMethod(ClassBuilder decorator, IMethodSymbol method)
    {
        var builder = decorator.DefineMethod(method.Name);

        foreach (var parameter in method.Parameters)
            builder.WithParameter(parameter.Name, Qualified(parameter.Type));

        var arguments = string.Join(", ", method.Parameters.Select(p => p.Name));
        var forward = $"_inner.{method.Name}({arguments})";

        builder.AddStatement(Log(method.Name));

        if (method.ReturnsVoid)
            builder.AddStatement($"{forward};");
        else
            builder.Returns(Qualified(method.ReturnType)).AddStatement($"return {forward};");
    }

    private static void EmitProperty(ClassBuilder decorator, IPropertySymbol property)
        => decorator.DefineProperty(property.Name, Qualified(property.Type))
            .GetOnly()
            .WithGetterBody(Log(property.Name), $"return _inner.{property.Name};");

    private static string Log(string memberName)
        => $"global::System.Console.WriteLine(\"[log] {memberName}\");";

    private static string Qualified(ISymbol symbol)
        => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
}
